/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.aedenj.gradle.plugin.quality

import org.gradle.api.Project
import org.gradle.api.Plugin

class QualityPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'kotlin.quality.plugin.greeting'")
            }
        }
    }
}
