/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.aedenj.gradle.plugins

import org.gradle.kotlin.dsl.apply

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.jlleitschuh.gradle.ktlint.KtlintPlugin

class KotlinQualityPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        with(project) {
           apply<KtlintPlugin>()
        }
    }
}
