/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.aedenj.gradle.plugins

import org.assertj.core.api.Assertions.assertThat
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test

class KotlinQualityPluginTest {
    @Test fun `contains required plugins`() {
        val project = ProjectBuilder.builder().build()

        assertThat(project.plugins).isEmpty()
        project.plugins.apply("io.github.aedenj.gradle.plugins.kotlin-quality")
        assertThat(project.pluginManager.hasPlugin("org.jlleitschuh.gradle.ktlint")).isTrue()
    }
}
