/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.aedenj.gradle.plugins

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'kotlin.quality.plugin.greeting' plugin.
 */
class KotlinQualityPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.aedenj.gradle.plugins.kotlin-quality")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
