name: "Build"
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  validation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Gradle Caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/files-2.1
            ~/.gradle/caches/metadata-2.96
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 11
          cache: "gradle"
      - name: Build
        run: ./gradlew build --no-daemon